### ISSUE TITLE
Warning about missing 'measured cell counts' file

### ISSUE THREAD

**Issue by DukeOmicsAnalysis** [MRCIEU/godmc#14]
**04a-methylation_variables.sh (line 55)**: warns that the provided `${measured_cellcounts}` file is missing, even though it doesn't actually check if it's present (and in our case, it is present)

**Comment by burrowsk** [comment]
Hi, could you please send me your 04a log file and config file (kimberley.burrows@bristol.ac.uk).

**Comment by burrowsk** [comment]
Error message has been amended.
