### ISSUE TITLE
Unable to handle invariant Age variable

### ISSUE THREAD

**Issue by DukeOmicsAnalysis** [MRCIEU/godmc#15]
**resources/genetics/create_cellcounts_plink.R (line 131)** crashes if you are using a population with an invariant age.  

`coefficients(summary(fit1))[,"Pr(>|t|)"]["Age_numeric"]` will return an `NA` if your age is invariant, and it therefore checking if it's < 0.05 will return: `missing value where TRUE/FALSE needed`

**Comment by burrowsk** [comment]
Invariant age check now added and adjustment for age bypassed if found to be invariant.
