### ISSUE TITLE
16. Analysis of phase 1 candidate associations

### ISSUE THREAD

**Issue by yocra3** [MRCIEU/godmc#18]
Hi!

When I am running the script ./16b-control.sh I have the following error:

`./16b-control.sh: line 54: /panfs/panasas01/shared-godmc/godmc_phase2_analysis/scratch/frq/INMA.frq.tmp: No such file or directory
`

Here you have the full output:

`GoDMC version 0.1.1
Commit: 9a92ac0cc4c793e01415b431e647e7adc6ceadfe
Commit date: 2017-05-30 15:01:54 +0100
Current time: Fri Jun  2 09:02:06 CEST 2017

Please ensure your scripts are up to date.
If in doubt, run 'git pull'

Running positive control
Testing cis-region of

Running positive control - This involves testing the cis-region of cg07959070, extracting the top hit and performing GWAS with the cis-hit fitted as a covariate

There should be a strong signal at the cis region, and no evidence for population stratification in the GWAS

Probe is available in the data
./16b-control.sh: line 54: /panfs/panasas01/shared-godmc/godmc_phase2_analysis/scratch/frq/INMA.frq.tmp: No such file or directory`

**Comment by epzjlm** [comment]
Hi, 
Sorry about this. This issue has been fixed. Please run `git pull` and try again.
