### ISSUE TITLE
phase2: 16a-setup.sh crashes (bad keeplist.txt file)

### ISSUE THREAD

**Issue by DukeOmicsAnalysis** [MRCIEU/godmc#20]
I'm attempting to run step 16a on both Dunedin cohorts, but am encountering the following errr:

Error: Line 48 of --keep file has fewer tokens than expected.

Looking at the keeplist.txt file, I can see that there are some lines with a single numeric value (that does not match a FID or IID).

**Comment by epzjlm** [comment]
ok I now changed it. Please run `git pull` and try again.
