### ISSUE TITLE
Problems when uploading results from step 16

### ISSUE THREAD

**Issue by yocra3** [MRCIEU/godmc#21]
Hi,

I have experienced some problems when uploading results from step 16. When I run the script, I got the following error:

```
 ./check_upload.sh 16 upload

Checking log files for 16
Version required: 0.1.1
Version used: 0.1.1
Correct script version
16a-setup.sh completed successfully.
Version required: 0.1.1
Version used: 0.1.1
Correct script version
16b-control.sh completed successfully.
Version required: 0.1.1
Version used: 0.1.1
Correct script version
16c-run.sh completed successfully for all batches

Checking results for 16
All phase 2 results present
Control results present

Section 16 has been successfully completed!

sshpass is not installed.
The results will now be archived, once that is done they will be uploaded to the server

Tarring results and log files
tar: invalid option -- e
Try `tar --help' or `tar --usage' for more information.
```

I took a look at code, and I found that there is an if that sets the args for tar command:

```
	if [ "${1}" = "17" ]
	then
		suff="tar"
		flags="cf"
	else
		suff="tgz"
		cmd="czf"
	fi
	tar ${flags} results/${study_name}_${1}.${suff} config resources/parameters results/${1}
```

${1} is the number passed to check_upload.sh. With this code, the flags are only set when ${1} is 17, i.e. for step 17. I manually changed the if and it worked and uploaded the results. However, I am not sure that our data was formatted how you were expecting. 

Could you check this code and the data we sent? We are INMA cohort.

**Comment by explodecomputer** [comment]
Thanks for this @yocra3 it has now been fixed
