### ISSUE TITLE
imputed using minimac

### ISSUE THREAD

**Issue by ejh243** [MRCIEU/godmc#5]
In the config file what should I set for imputation quality scores and quality type? (rows 29 and 32?)

**Comment by explodecomputer** [comment]
hey i guess these sections?

```
# Imputation quality scores
# This should be a file with three columns, SNP, MAF and quality scores
quality_scores="${home_directory}/input_data/data.info"

# The software used to to estimate imputation quality
quality_type="impute2"
```

if you are using minimac imputed data then create a file called e.g. `data.info`, with three columns where the quality scores column is the rsq value. and the quality_type can be set to `minimac`
