### ISSUE TITLE
Normalization with meffil, code error

### ISSUE THREAD

**Issue by elecarnero** [MRCIEU/godmc#6]
Hi. I found a small error in the code from the section: normalised methylation data (using meffil)

save(norm.objects,file=paste(norm.obj.pc",pc,".Robj",sep=""))
should be written as
save(norm.objects,file=paste("norm.obj.pc",pc,".Robj",sep=""))
:)

**Comment by epzjlm** [comment]
thanks! I updated the wiki

**Comment by elecarnero** [comment]
Hi. Here another typo in the wiki:

norm.objects <- meffil.normalize.quantiles(qc.objects, number.pcs=pc)
save(norm.objects,file=paste("norm.obj.pc",pc,".Robj",sep=""))

norm.beta <- meffil.normalize.samples(norm.objects, cpglist.remove=qc.summary$bad.cpgs$name)
save(norm.objects,file=paste("norm.obj.pc",pc,".Robj",sep=""))

the file to save in norm.beta should be norm.beta and the name to save it should be paste("norm.beta.pc",pc,".Robj",sep="") to avoid overwrite the pre-existing norm.objects

thanks!

**Comment by epzjlm** [comment]
thanks! Fixed it!
