### ISSUE TITLE
methylation levels & PCs

### ISSUE THREAD

**Issue by elecarnero** [MRCIEU/godmc#7]
[pc.fit.pdf](https://github.com/MRCIEU/godmc/files/53318/pc.fit.pdf)

Hi. I obtained the following plot for the mean squared residuals explained by each PC of the methylation matrix. I see 3 major drops in variance , one at 8 PCs, another at 10 and a minor one at 15 PCs. It is not very clear to me how to make the decision on the numbers of PCs based on this. How many would you use to adjust the methylation levels? Thanks!

**Comment by epzjlm** [comment]
I would do 15 pcs as it doesn't harm to include a bit more.
