### ISSUE TITLE
Missing script: harmonization.R

### ISSUE THREAD

**Issue by luijkr** [MRCIEU/godmc#8]
Hi there. When running 02a-snp_data.sh, the following file seems to be missing: resources/genetics/harmonization.R

**Comment by epzjlm** [comment]
Hi rene,

I am currently extending this script to do some more recoding and adding some more data cleaning steps.

**Comment by epzjlm** [comment]
I now uploaded the harmonisation script which worked fine on ARIES. Please try. This script will be updated in a separate branch.
