### ISSUE TITLE
Missingness in phenotype data

### ISSUE THREAD

**Issue by luijkr** [MRCIEU/godmc#9]
Hi there! In the LLS data a little over 10% (10.5%) of height and BMI are missing, giving a warning telling me to address this issue. Previously I just substituted the mean height/BMI, so the scripts would run - not the ideal scenario. However, I cannot possibly deal with this issue, the data just isn't there and I don't think they will be in the (near) future. Therefore, uploading the new results also isn't possible. Thoughts?

**Comment by explodecomputer** [comment]
hey rené good point, i think this should just be a warning and not an error. will change it now

**Comment by explodecomputer** [comment]
ok that should work now. i'm just gonna try to restructure this a little so that it is broken down into sections, e.g. check genetic data, methylation data, cnv data, covariate data, phenotype data, installed packages will be separate
